# Generated by Django 5.2.7 on 2025-11-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroMarket', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/products/'),
        ),
    ]
