# Generated by Django 5.2.7 on 2025-11-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroMarket', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
