# Generated by Django 5.2.7 on 2025-11-06 04:54

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectroMarket', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='products/'),
        ),
    ]
